#!/usr/bin/env bash
# Copies the generated JSON schemas from ../docs into ./schemas so the
# extension ships a self-contained copy that works offline.
#
# The schemas in ../docs are generated by the cfg crate's build script
# (crates/cfg/build/json_schema_builder.rs) - run `cargo build -p cfg`
# (or a full workspace build) first if they might be stale.
set -euo pipefail
cd "$(dirname "$0")"

cp ../docs/pipeline_template.schema.json schemas/pipeline_template.schema.json
cp ../docs/project.schema.json schemas/project.schema.json
cp ../docs/project_template.schema.json schemas/project_template.schema.json

echo "Schemas synced from ../docs into ./schemas"
