import type { JsonSchema } from "./types";

const DEFS_PREFIX = "#/$defs/";

/**
 * Resolves a schema node's `$ref`, if any, against `$defs`.
 *
 * The bundled schemas are generated by schemars from Rust enums, which
 * produces JSON Schema 2020-12 nodes where `$ref` sits *alongside* sibling
 * keywords rather than alone, e.g.:
 *
 *   { "type": "object", "properties": { "type": { "const": "blur" } },
 *     "required": ["type"], "$ref": "#/$defs/BlurSettings" }
 *
 * Per 2020-12 semantics (unlike draft-07) all sibling keywords still apply,
 * so the effective schema is the *merge* of the referenced def and the
 * node's own keywords - not a plain replacement. This walks that merge
 * (following chained refs) and returns a ref-free schema.
 */
export function resolveSchema(schema: JsonSchema, defs: Record<string, JsonSchema>): JsonSchema {
  if (!schema.$ref) {
    return schema;
  }

  if (!schema.$ref.startsWith(DEFS_PREFIX)) {
    throw new Error(`Unsupported $ref target: ${schema.$ref}`);
  }

  const defName = schema.$ref.slice(DEFS_PREFIX.length);
  const target = defs[defName];
  if (!target) {
    throw new Error(`Unknown schema definition: ${defName}`);
  }

  const resolvedTarget = resolveSchema(target, defs);
  const overlay: JsonSchema = { ...schema };
  delete overlay.$ref;
  return mergeSchemas(resolvedTarget, overlay);
}

/** Merges an overlay schema over a base schema; overlay wins on conflicts. */
function mergeSchemas(base: JsonSchema, overlay: JsonSchema): JsonSchema {
  const required = dedupe([...(base.required ?? []), ...(overlay.required ?? [])]);

  return {
    ...base,
    ...overlay,
    description: overlay.description ?? base.description,
    default: overlay.default !== undefined ? overlay.default : base.default,
    properties:
      base.properties || overlay.properties
        ? { ...(base.properties ?? {}), ...(overlay.properties ?? {}) }
        : undefined,
    required: required.length > 0 ? required : undefined,
  };
}

function dedupe(values: string[]): string[] {
  return Array.from(new Set(values));
}
